// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbL9aDhafQjYgr6YOZjfAWluM2GXefDcE',
    appId: '1:506140763138:web:4e4288726a0d633f09731b',
    messagingSenderId: '506140763138',
    projectId: 'talyen-store',
    authDomain: 'talyen-store.firebaseapp.com',
    storageBucket: 'talyen-store.appspot.com',
    measurementId: 'G-DWDBPE4DVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5YIdWQeNb_EnE_bA9KtDqaHOGQhKIS_w',
    appId: '1:506140763138:android:99d8b524fcddd8bb09731b',
    messagingSenderId: '506140763138',
    projectId: 'talyen-store',
    storageBucket: 'talyen-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmVLXMjt1hTfJNKV7RDBLAwBpwGHqziVE',
    appId: '1:506140763138:ios:1f03b941e2fc747609731b',
    messagingSenderId: '506140763138',
    projectId: 'talyen-store',
    storageBucket: 'talyen-store.appspot.com',
    iosBundleId: 'com.example.talyenStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmVLXMjt1hTfJNKV7RDBLAwBpwGHqziVE',
    appId: '1:506140763138:ios:0b9d3d3b1079f24209731b',
    messagingSenderId: '506140763138',
    projectId: 'talyen-store',
    storageBucket: 'talyen-store.appspot.com',
    iosBundleId: 'com.example.talyenStore.RunnerTests',
  );
}
